### ISSUE TITLE
Error when making build

### ISSUE THREAD

**Issue by josipbernat** [lunastorm/webrtc-ios#1]
Hi,

I've discovered your script from webRTC Google Groups discussion. So I cloned your repository and run "make -j4" command from terminal. After 30, 40minutes I get following error:

AssertionError: Multiple codesigning fingerprints for identity: iPhone Developer
Error: Command /usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /Users/PATH_TO_REPO/webrtc-ios/build/webrtc
make: *** [build/webrtc-arm/Release-iphoneos] Error 2
rm build/libvpx-arm64make: unlink: build/libvpx-arm64: Operation not permitted
 build/libvpx.x86.a build/libvpxsub-armv7.a build/libvpxsub-arm64.a build/libvpx-armv7make: unlink: build/libvpx-armv7: Operation not permitted
 build/webrtc-arm/Release-iphoneosmake: unlink: build/webrtc-arm/Release-iphoneos: Operation not permitted
 build/libvpx-x86_64make: unlink: build/libvpx-x86_64: Operation not permitted
 build/libvpx-i386make: unlink: build/libvpx-i386: Operation not permitted
 build/libvpx.arm.a build/libvpxsub-x86_64.a build/libvpxsub-i386.a

**Comment by lunastorm** [comment]
the new script has been updated
